TOLERANCE_DAYS = 1

MIN_ENTITY_LENGTH = 2

NOISE_WORDS = {
    "will", "the", "a", "an", "be", "to", "in", "on", "by", "at",
    "what", "who", "which", "when", "is", "are", "was", "were",
    "market", "prediction", "bet", "odds", "win", "winner", "s"
}

UNWANTED_ENT_LABELS = {
    "DATE", "MONEY", "PERCENT", "QUANTITY", "CARDINAL"
}

NFL_TEAMS = {
    "arizona cardinals": ["arizona cardinals", "cardinals", "az cardinals", "ari"],
    "atlanta falcons": ["atlanta falcons", "falcons", "atl"],
    "baltimore ravens": ["baltimore ravens", "ravens", "bal"],
    "buffalo bills": ["buffalo bills", "bills", "buf"],
    "carolina panthers": ["carolina panthers", "panthers", "car"],
    "chicago bears": ["chicago bears", "bears", "chi"],
    "cincinnati bengals": ["cincinnati bengals", "bengals", "cin"],
    "cleveland browns": ["cleveland browns", "browns", "cle"],
    "dallas cowboys": ["dallas cowboys", "cowboys", "dal"],
    "denver broncos": ["denver broncos", "broncos", "den"],
    "detroit lions": ["detroit lions", "lions", "det"],
    "green bay packers": ["green bay packers", "packers", "gb"],
    "houston texans": ["houston texans", "texans", "hou"],
    "indianapolis colts": ["indianapolis colts", "colts", "ind"],
    "jacksonville jaguars": ["jacksonville jaguars", "jaguars", "jax"],
    "kansas city chiefs": ["kansas city chiefs", "chiefs", "kc"],
    "las vegas raiders": ["las vegas raiders", "raiders", "lv"],
    "los angeles chargers": ["los angeles chargers", "la chargers", "chargers", "lac"],
    "los angeles rams": ["los angeles rams", "la rams", "rams", "lar"],
    "miami dolphins": ["miami dolphins", "dolphins", "mia"],
    "minnesota vikings": ["minnesota vikings", "vikings", "min"],
    "new england patriots": ["new england patriots", "patriots", "ne"],
    "new orleans saints": ["new orleans saints", "saints", "no nfl"],
    "new york giants": ["new york giants", "ny giants", "giants", "nyg"],
    "new york jets": ["new york jets", "ny jets", "jets", "nyj"],
    "philadelphia eagles": ["philadelphia eagles", "eagles", "phi"],
    "pittsburgh steelers": ["pittsburgh steelers", "steelers", "pit"],
    "san francisco 49ers": ["san francisco 49ers", "49ers", "niners", "sf"],
    "seattle seahawks": ["seattle seahawks", "seahawks", "sea"],
    "tampa bay buccaneers": ["tampa bay buccaneers", "buccaneers", "bucs", "tb"],
    "tennessee titans": ["tennessee titans", "titans", "ten"],
    "washington commanders": ["washington commanders", "commanders", "was"],
}

NBA_TEAMS = {
    "boston celtics": ["boston celtics", "celtics", "bos"],
    "brooklyn nets": ["brooklyn nets", "nets", "bkn"],
    "new york knicks": ["new york knicks", "ny knicks", "knicks", "nyk"],
    "philadelphia 76ers": ["philadelphia 76ers", "76ers", "sixers", "phi nba"],
    "toronto raptors": ["toronto raptors", "raptors", "tor"],
    "chicago bulls": ["chicago bulls", "bulls", "chi nba"],
    "cleveland cavaliers": ["cleveland cavaliers", "cavaliers", "cavs", "cle nba"],
    "detroit pistons": ["detroit pistons", "pistons", "det nba"],
    "indiana pacers": ["indiana pacers", "pacers", "ind nba"],
    "milwaukee bucks": ["milwaukee bucks", "bucks", "mil"],
    "atlanta hawks": ["atlanta hawks", "hawks", "atl nba"],
    "charlotte hornets": ["charlotte hornets", "hornets", "cha"],
    "miami heat": ["miami heat", "heat", "mia nba"],
    "orlando magic": ["orlando magic", "magic", "orl"],
    "washington wizards": ["washington wizards", "wizards", "was nba"],
    "denver nuggets": ["denver nuggets", "nuggets", "den nba"],
    "minnesota timberwolves": ["minnesota timberwolves", "timberwolves", "wolves", "min nba"],
    "oklahoma city thunder": ["oklahoma city thunder", "thunder", "okc"],
    "portland trail blazers": ["portland trail blazers", "trail blazers", "blazers", "por"],
    "utah jazz": ["utah jazz", "jazz", "uta"],
    "golden state warriors": ["golden state warriors", "warriors", "gsw"],
    "los angeles clippers": ["los angeles clippers", "la clippers", "clippers", "lac nba"],
    "los angeles lakers": ["los angeles lakers", "la lakers", "lakers", "lal"],
    "phoenix suns": ["phoenix suns", "suns", "phx"],
    "sacramento kings": ["sacramento kings", "sacramento kings nba", "kings nba", "sac"],
    "dallas mavericks": ["dallas mavericks", "mavericks", "mavs", "dal nba"],
    "houston rockets": ["houston rockets", "rockets", "hou nba"],
    "memphis grizzlies": ["memphis grizzlies", "grizzlies", "mem"],
    "new orleans pelicans": ["new orleans pelicans", "pelicans", "nop"],
    "san antonio spurs": ["san antonio spurs", "spurs", "sas"],
}

MLB_TEAMS = {
    "arizona diamondbacks": ["arizona diamondbacks", "diamondbacks", "dbacks", "ari mlb"],
    "atlanta braves": ["atlanta braves", "braves", "atl mlb"],
    "baltimore orioles": ["baltimore orioles", "orioles", "bal mlb"],
    "boston red sox": ["boston red sox", "red sox", "bos mlb"],
    "chicago cubs": ["chicago cubs", "cubs", "chc"],
    "chicago white sox": ["chicago white sox", "white sox", "cws"],
    "cincinnati reds": ["cincinnati reds", "reds", "cin mlb"],
    "cleveland guardians": ["cleveland guardians", "guardians", "cle mlb"],
    "colorado rockies": ["colorado rockies", "rockies", "col"],
    "detroit tigers": ["detroit tigers", "tigers", "det mlb"],
    "houston astros": ["houston astros", "astros", "hou mlb"],
    "kansas city royals": ["kansas city royals", "royals", "kc mlb"],
    "los angeles angels": ["los angeles angels", "la angels", "angels", "laa"],
    "los angeles dodgers": ["los angeles dodgers", "la dodgers", "dodgers", "lad"],
    "miami marlins": ["miami marlins", "marlins", "mia mlb"],
    "milwaukee brewers": ["milwaukee brewers", "brewers", "mil mlb"],
    "minnesota twins": ["minnesota twins", "twins", "min mlb"],
    "new york mets": ["new york mets", "ny mets", "mets", "nym"],
    "new york yankees": ["new york yankees", "ny yankees", "yankees", "nyy"],
    "oakland athletics": ["oakland athletics", "athletics", "a's", "oak"],
    "philadelphia phillies": ["philadelphia phillies", "phillies", "phi mlb"],
    "pittsburgh pirates": ["pittsburgh pirates", "pirates", "pit mlb"],
    "san diego padres": ["san diego padres", "padres", "sd"],
    "san francisco giants": ["san francisco giants", "sf giants", "giants mlb", "sf mlb"],
    "seattle mariners": ["seattle mariners", "mariners", "sea mlb"],
    "st louis cardinals": ["st louis cardinals", "st. louis cardinals", "cardinals mlb", "stl"],
    "tampa bay rays": ["tampa bay rays", "rays", "tb mlb"],
    "texas rangers": ["texas rangers", "rangers mlb", "tex"],
    "toronto blue jays": ["toronto blue jays", "blue jays", "tor mlb"],
    "washington nationals": ["washington nationals", "nationals", "was mlb"],
}

NHL_TEAMS = {
    "anaheim ducks": ["anaheim ducks", "ducks", "ana"],
    "boston bruins": ["boston bruins", "bruins", "bos nhl"],
    "buffalo sabres": ["buffalo sabres", "sabres", "buf nhl"],
    "calgary flames": ["calgary flames", "flames", "cgy"],
    "carolina hurricanes": ["carolina hurricanes", "hurricanes", "canes", "car nhl"],
    "chicago blackhawks": ["chicago blackhawks", "blackhawks", "chi nhl"],
    "colorado avalanche": ["colorado avalanche", "avalanche", "avs", "col nhl"],
    "columbus blue jackets": ["columbus blue jackets", "blue jackets", "cbj"],
    "dallas stars": ["dallas stars", "stars", "dal nhl"],
    "detroit red wings": ["detroit red wings", "red wings", "det nhl"],
    "edmonton oilers": ["edmonton oilers", "oilers", "edm"],
    "florida panthers": ["florida panthers", "panthers nhl", "fla"],
    "los angeles kings": ["los angeles kings", "la kings", "kings nhl", "lak"],
    "minnesota wild": ["minnesota wild", "wild", "min nhl"],
    "montreal canadiens": ["montreal canadiens", "canadiens", "habs", "mtl"],
    "nashville predators": ["nashville predators", "predators", "preds", "nsh"],
    "new jersey devils": ["new jersey devils", "devils", "njd"],
    "new york islanders": ["new york islanders", "ny islanders", "islanders", "nyi"],
    "new york rangers": ["new york rangers", "ny rangers", "rangers nhl", "nyr"],
    "ottawa senators": ["ottawa senators", "senators", "sens", "ott"],
    "philadelphia flyers": ["philadelphia flyers", "flyers", "phi nhl"],
    "pittsburgh penguins": ["pittsburgh penguins", "penguins", "pens", "pit nhl"],
    "san jose sharks": ["san jose sharks", "sharks", "sjs"],
    "seattle kraken": ["seattle kraken", "kraken", "sea nhl"],
    "st louis blues": ["st louis blues", "st. louis blues", "blues", "stl nhl"],
    "tampa bay lightning": ["tampa bay lightning", "lightning", "bolts", "tb nhl"],
    "toronto maple leafs": ["toronto maple leafs", "maple leafs", "leafs", "tor nhl"],
    "utah hockey club": ["utah hockey club", "utah hc", "uta nhl"],
    "vancouver canucks": ["vancouver canucks", "canucks", "van"],
    "vegas golden knights": ["vegas golden knights", "golden knights", "vgk"],
    "washington capitals": ["washington capitals", "capitals", "caps", "was nhl"],
    "winnipeg jets": ["winnipeg jets", "jets nhl", "wpg"],
}

AMBIGUOUS_ALIASES = {

    "giants",
    "rangers",
    "jets",
    "kings",
    "cardinals",
    "panthers",
}

MONTHS = {
    'jan': '01', 'january': '01', 'feb': '02', 'february': '02',
    'mar': '03', 'march': '03', 'apr': '04', 'april': '04',
    'may': '05', 'jun': '06', 'june': '06', 'jul': '07', 'july': '07',
    'aug': '08', 'august': '08', 'sep': '09', 'september': '09',
    'oct': '10', 'october': '10', 'nov': '11', 'november': '11',
    'dec': '12', 'december': '12'
}

DAYS = {
    "first": 1,
    "second": 2,
    "third": 3,
    "fourth": 4,
    "fifth": 5,
    "sixth": 6,
    "seventh": 7,
    "eighth": 8,
    "ninth": 9,
    "tenth": 10,
    "eleventh": 11,
    "twelfth": 12,
    "thirteenth": 13,
    "fourteenth": 14,
    "fifteenth": 15,
    "sixteenth": 16,
    "seventeenth": 17,
    "eighteenth": 18,
    "nineteenth": 19,
    "twentieth": 20,
    "twenty-first": 21,    "twenty first": 21,
    "twenty-second": 22,    "twenty second": 22,
    "twenty-third": 23,    "twenty third": 23,
    "twenty-fourth": 24,    "twenty fourth": 24,
    "twenty-fifth": 25,    "twenty fifth": 25,
    "twenty-sixth": 26,    "twenty sixth": 26,
    "twenty-seventh": 27,    "twenty seventh": 27,
    "twenty-eighth": 28,    "twenty eighth": 28,
    "twenty-ninth": 29, "twenty ninth": 29, 
    "thirtieth": 30,
    "thirty-first": 31, "thirty first": 31,
}

YEARS = [
    "2026",
    "2027",
    "2028",
    "2029",
    "2030",
    "2031",
    "2032",
    "2033",
    "2034",
    "2035",
    "2036",
]

NEGATION_WORDS = {
        "not", "never", "cannot", "no longer", "no deal", "unable",
        "fail", "fails", "failed",
        "won t", "doesn t", "didn t", "isn t", "wasn t",
        "wouldn t", "shouldn t", "couldn t", "aren t", "weren t",
        "hasn t", "haven t", "can t",
    }

KEYWORD_GROUPS = [
    # --- Award/title names (NER mis-tags these as FAC/ORG/nothing - confirmed) ---
    {"golden ball", "ballon d'or", "ballon dor", "golden boot", "silver ball",
     "silver boot", "bronze ball", "bronze boot", "golden glove", "best player",
     "player of the tournament", "top goalscorer", "top scorer",
     "leading scorer", "mvp", "most valuable player"},
    {"heisman", "heisman trophy"},
    {"nobel prize", "nobel peace prize", "nobel prize winner"},
    {"oscar", "academy award", "academy awards"},
    {"grammy", "grammy award", "grammy awards"},
    {"mvp award"},  # sports league regular-season/finals MVP, distinct from tournament MVP above
    {"cy young", "cy young award"},
    {"rookie of the year"},
    {"defensive player of the year"},
    {"coach of the year", "manager of the year"},
    {"pulitzer", "pulitzer prize"},

    # --- Recurring event types (structural, not tied to any one edition/year) ---
    {"world cup", "fifa world cup"},
    {"super bowl", "superbowl"},
    {"olympics", "olympic games", "summer olympics", "winter olympics"},
    {"champions league", "uefa champions league"},
    {"europa league", "uefa europa league"},
    {"nba finals"},
    {"stanley cup", "stanley cup finals"},
    {"world series", "mlb world series"},
    {"ncaa tournament", "march madness"},
    {"us open"},
    {"wimbledon"},
    {"french open", "roland garros"},
    {"australian open"},
    {"nfl draft"},
    {"nba draft"},
    {"mlb draft"},
    {"ryder cup"},
    {"presidents cup"},
    {"kentucky derby"},
    {"indy 500", "indianapolis 500"},
    {"daytona 500"},
    {"tour de france"},
    {"copa america"},
    {"euro 2028", "european championship", "uefa euro"},
    {"gold cup", "concacaf gold cup"},
    {"pro bowl"},
    {"mls cup"},

    # --- US monetary policy / economic indicators ---
    {"fed", "fomc", "federal reserve", "fed rate", "federal funds rate",
     "interest rate decision", "interest rate", "rate cut", "rate hike",
     "rate cuts", "rate hikes"},
    {"nonfarm payroll", "nonfarm payrolls", "jobs report", "jobs added",
     "jobs created", "unemployment rate", "unemployment"},
    {"cpi", "inflation report", "consumer price index", "inflation rate"},
    {"ppi", "producer price index"},
    {"pce", "core pce", "personal consumption expenditures"},
    {"gdp report", "gdp growth", "gross domestic product"},
    {"retail sales"},
    {"consumer confidence"},
    {"jobless claims", "initial jobless claims"},
    {"housing starts", "housing start"},
    {"existing home sales", "new home sales"},
    {"ism", "ism manufacturing", "ism services"},
    {"recession", "economic recession"},
    {"treasury yield", "10 year yield", "10-year yield", "yield curve"},
    {"quantitative easing", "quantitative tightening"},

    # --- Elections / US government ---
    {"election", "presidential election", "general election"},
    {"primary election", "presidential primary"},
    {"midterm election", "midterms"},
    {"electoral college", "electoral votes"},
    {"impeachment", "impeach"},
    {"government shutdown", "shutdown"},
    {"debt ceiling", "debt limit"},
    {"government funding", "federal funding"},
    {"supreme court", "supreme court ruling"},
    {"executive order", "executive orders"},
    {"confirmation hearing", "senate confirmation"},
    {"cabinet nomination", "cabinet pick"},
    {"filibuster"},
    {"special election"},
    {"recall election"},

    # --- Financial markets / corporate events ---
    {"ipo", "initial public offering"},
    {"stock split", "stock split announcement"},
    {"earnings report", "earnings call", "quarterly earnings",
     "earnings results"},
    {"merger", "acquisition", "merger and acquisition", "m&a"},
    {"bankruptcy", "bankruptcy filing"},
    {"dividend", "dividend payment"},
    {"buyback", "stock buyback", "share buyback"},
    {"spinoff", "spin-off"},
    {"delisting", "delisted"},
    {"short squeeze"},
    {"sec investigation", "sec probe"},
    {"antitrust", "antitrust lawsuit"},

    # --- Crypto / financial assets ---
    {"bitcoin", "btc"},
    {"ethereum", "eth"},
    {"solana", "sol"},
    {"xrp", "ripple"},
    {"dogecoin", "doge"},
    {"cardano", "ada"},
    {"binance coin", "bnb"},
    {"litecoin", "ltc"},
    {"polkadot", "dot"},
    {"chainlink", "link"},
    {"stablecoin", "stablecoins"},
    {"crypto etf", "spot etf", "bitcoin etf", "ethereum etf"},
    {"halving", "bitcoin halving"},
    {"memecoin", "meme coin"},
    {"nasdaq", "nasdaq composite"},
    {"s&p 500", "s&p500", "sp500"},
    {"dow jones", "dow", "djia"},
    {"russell 2000"},
    {"vix"},
    {"ftse 100"},
    {"nikkei 225"},
    {"crude oil", "wti crude"},
    {"brent crude"},
    {"gold price", "price of gold"},
    {"silver price", "price of silver"},
    {"nvidia", "nvda"},
    {"tesla", "tsla"},
    {"apple", "aapl"},
    {"microsoft", "msft"},
    {"amazon", "amzn"},
    {"alphabet", "google", "googl", "goog"},
    {"meta", "meta platforms"},
    {"openai"},
    {"berkshire hathaway", "brk.a", "brk.b"},
    {"netflix", "nflx"},
    {"broadcom", "avgo"},
    {"amd"},
    {"intel", "intc"},
    {"coinbase", "coin"},
    {"palantir", "pltr"},

    # --- International conflict / diplomacy ---
    {"ceasefire", "cease-fire", "peace deal", "peace agreement"},
    {"nuclear deal", "nuclear agreement", "nuclear talks"},
    {"sanctions", "economic sanctions"},
    {"nato", "north atlantic treaty organization"},
    {"united nations", "un", "un security council"},
    {"tariff", "tariffs", "trade tariff", "trade war"},
    {"peace talks", "peace negotiations"},
    {"military aid", "foreign aid"},
    {"invasion"},
    {"airstrike", "air strikes", "airstrikes"},
    {"coup", "coup d'etat"},
    {"regime change"},
    {"assassination", "assassinated"},
    {"hostage deal", "hostage release"},
    {"troop withdrawal"},
    {"annexation", "annexed"},

    # --- Hyphenated / cross-entity geopolitical phrasing (confirmed NER blind spot) ---
    {"us-iran", "u.s.-iran", "us and iran"},
    {"us-china", "u.s.-china", "us and china"},
    {"us-russia", "u.s.-russia", "us and russia"},
    {"us-israel", "u.s.-israel", "us and israel"},
    {"israel-hamas", "israel and hamas"},
    {"russia-ukraine", "russia and ukraine"},
    {"china-taiwan", "china and taiwan"},
    {"north korea-south korea", "north korea and south korea"},
    {"israel-iran", "israel and iran"},
    {"india-pakistan", "india and pakistan"},
    {"us-venezuela", "u.s.-venezuela", "us and venezuela"},
    {"us-cuba", "u.s.-cuba", "us and cuba"},
    {"us-mexico", "u.s.-mexico", "us and mexico"},
    {"eu-uk", "eu and uk"},

    # --- Product/version jargon (NER has no PRODUCT category reliability here) ---
    {"gpt-6", "gpt6", "gpt 6"},
    {"gpt-5", "gpt5", "gpt 5"},
    {"claude", "mythos", "opus", "sonnet"},
    {"gemini"},
    {"llama"},
    {"grok"},
    {"deepseek"},
    {"qwen"},
    {"mistral ai", "mistral"},
    {"copilot"},
    {"gta vi", "gta6", "gta 6"},

    # --- Technology / AI releases ---
    {"artificial intelligence", "artificial intelligence model", "ai model"},
    {"large language model", "large language models", "llm", "llms"},
    {"chatgpt"},
    {"openai model", "openai models"},
    {"anthropic model", "anthropic models"},
    {"google ai", "google deepmind"},
    {"ai agent", "ai agents"},
    {"robotaxi", "robotaxis"},
    {"self-driving", "self driving", "autonomous driving"},
    {"agi", "artificial general intelligence"},
    {"superintelligence"},
    {"ai regulation", "ai safety"},
    {"humanoid robot", "humanoid robots"},

    # --- Major sports statistics / outcomes ---
    {"touchdown", "touchdowns"},
    {"home run", "home runs"},
    {"passing yards", "rushing yards", "receiving yards"},
    {"points per game", "ppg"},
    {"goals scored", "goals"},
    {"assists"},
    {"rebounds"},
    {"strikeouts", "strikeout"},
    {"wins", "win total"},
    {"regular season", "regular-season"},
    {"playoffs", "playoff"},
    {"championship", "championship game"},
    {"no hitter", "no-hitter"},
    {"perfect game"},
    {"triple double", "triple-double"},
    {"hat trick"},

    # --- Major entertainment releases / awards ---
    {"box office", "domestic box office", "worldwide box office"},
    {"opening weekend", "opening weekend box office"},
    {"streaming", "streaming release"},
    {"emmy", "emmy award", "emmy awards"},
    {"tony award", "tony awards"},
    {"bafta", "bafta awards"},
    {"golden globe", "golden globes"},
    {"sag award", "sag awards"},
    {"billboard chart", "billboard 200", "billboard hot 100"},
    {"number one album", "number one single"},
    {"rotten tomatoes"},

    # --- Weather / natural events ---
    {"hurricane", "tropical storm"},
    {"tornado", "tornadoes"},
    {"earthquake", "earthquakes"},
    {"wildfire", "wildfires"},
    {"landfall"},
    {"category 5", "category five"},
    {"blizzard"},
    {"heat wave", "heatwave"},
    {"drought"},
    {"flooding", "flood"},

    # --- Space / launches ---
    {"spacex", "space x"},
    {"falcon 9", "falcon nine"},
    {"starship", "spacex starship"},
    {"rocket launch", "rocket launches"},
    {"moon landing", "lunar landing"},
    {"mars mission"},
    {"iss", "international space station"},
    {"artemis", "artemis program"},
    {"nasa"},
    {"blue origin"},
    {"satellite launch"},
]